apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: agent
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: account
          image: docker.io/metinseylan/stackdriver-trace-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1923
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: agent
  name: agent
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 1923
  selector:
    app: agent
